#!/bin/bash

#To use this script, open the Terminal app and go to the directry
#where this script is located and excecute the following commands:
	# chmod u+x PleaseSleep

	# ./PleaseSleep install
	# -------- OR ---------
	# ./PleaseSleep remove

# Get the argument
set -e
ARG=$1

# quit if any command fails
if [ -z "$1" ] ; then
	echo "Error: No parameter. Use 'PleaseSleep install' or 'PleaseSleep remove'."
	exit 1


# REMOVE EVERYTHING
elif [ "$ARG" == "remove" ] || [ "$ARG" == "uninstall" ]
then
	echo
	echo
	echo "REMOVING PleaseSleep with sleepwatcher 2.2"
	echo "This will remove all PleaseSleep AND all Sleepwatcher files."
	echo "This also includes the sleep and wake scripts."
	echo
	echo "Are you sure you want to continue?"
	echo "Press Enter to continue or Crtl+c to quit"
	read
	echo "-------------------------------------------------------------------"
	echo

	echo "Unloading the LaunchAgent..."
	launchctl unload ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist &> /dev/null
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Removing sleep and wake scripts ..."
	rm ~/.sleep &> /dev/null
	rm ~/.wakeup &> /dev/null
    rm -rf ~/Desktop/BadNetwork.app &> /dev/null
    rm ~/.badwifinetworks &> /dev/null
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Removing Sleepwatcher 2.2 and all the files ..."
	brew uninstall sleepwatcher
    brew cleanup

	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "-------------------------------------------------------------------"
	echo

	echo "PleaseSleep and Sleepwatcher 2.2 are successfully removed from your lovely Mac!!"
	echo
	echo
	echo


# INSTALL EVERYTHING
elif [ "$1" == "install" ]
then
	echo
	echo
	echo "INSTALLING PleaseSleep with sleepwatcher 2.2"
	echo
	echo "Are you sure you want to continue?"
	echo "Press Enter to continue or Crtl+c to quit"
	read
	echo "-------------------------------------------------------------------"
	echo

	echo "Gaining permissions for /usr/local ..."
	# source: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md
	sudo chown -R $(whoami):admin /usr/local
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Installing Sleepwatcher 2.2 (using the brew command)."
	echo "Please follow the instructions when prompted ..."
	echo "(Press ENTER key to continue.)"
	read
	echo
	brew install sleepwatcher --quiet
	echo
	echo
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Creating the sleep/wake script ..."
        cp {.wakeup,.sleep} ~/
				chmod u+x ~/{.wakeup,.sleep}
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo



    touch ~/.badwifinetworks
    unzip automator.zip BadNetwork.app/* -d ~/Desktop


	echo "Copying *.plist file to ~/Library/LaunchAgents ..."
	cp /usr/local/Cellar/sleepwatcher/2.2/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist ~/Library/LaunchAgents
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Starting PleaseSleep"
	launchctl load ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo
	echo
	echo "-------------------------------------------------------------------"
	echo
	echo "Path to wake script: ~/.wakeup"
	echo "Path to sleep script: ~/.sleep"
	echo "Path to logging file: /tmp/sleep.log"
	echo
	echo "Note that WiFi will only turn on 7 seconds AFTER your Mac has been waked"
	echo
	echo "-------------------------------------------------------------------"
	echo
	echo
	echo
	echo "IF NO ERRORS WERE FOUND, THEN INSTALLATION IS COMPLETE."
	echo
	echo "Your lovely Mac will sleep like a boss now!"
	echo
	echo
	echo

fi
